#!/usr/bin/env bash

# =============================================================================
# MyScene — local development setup
#
# Sets up everything needed to run the project on THIS machine:
#   1. System packages (PHP + pdo_mysql, Composer, Node.js, npm, MariaDB)
#   2. Composer dependencies (repo root) and npm dependencies (api/server)
#   3. The local database: MariaDB running, schema imported, dedicated
#      'myscene' MySQL user (reuses scripts/dbUpdate.sh)
#   4. .env scaffolding:
#        .env              DB credentials for the PHP db-api (repo root)
#        api/server/.env   Node API config (points DB_API_BASE_URL at
#                          http://127.0.0.1:8080, the local PHP db-api)
#      Existing .env files are never overwritten.
#
# After this, start three processes (three terminals) and open
# http://localhost:8000 :
#
#   php -S localhost:8080 -t api/db     # PHP db-api (talks to MySQL)
#   cd api/server && npm start          # Node API on http://localhost:3000
#   php -S localhost:8000 -t public     # Website
#
# The pages default to the production API (https://api.myscene.live). To use
# the local Node API instead, set window.MYSCENE_API_BASE = 'http://localhost:3000'
# in each page before the site scripts load (see public/js/api.js).
#
# Usage:  ./install.sh
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

log()  { echo "[myscene] $*"; }
warn() { echo "[myscene][WARN] $*" >&2; }
die()  { echo "[myscene][ERROR] $*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

SUDO=""
if [ "$(id -u)" -ne 0 ]; then
    if have sudo; then SUDO="sudo"; else
        die "This script needs root (or passwordless sudo)."
    fi
fi

apt_install() {
    local missing=()
    for pkg in "$@"; do
        dpkg -s "$pkg" >/dev/null 2>&1 || missing+=("$pkg")
    done
    [ ${#missing[@]} -eq 0 ] && return 0
    log "Installing packages: ${missing[*]}"
    DEBIAN_FRONTEND=noninteractive $SUDO apt-get update -qq
    DEBIAN_FRONTEND=noninteractive $SUDO apt-get install -y --no-install-recommends "${missing[@]}"
}

# --- 1. System packages -------------------------------------------------------

PKGS=(git mariadb-server nodejs npm composer)
if ! have php; then
    PKGS+=(php)
fi
if ! php -m 2>/dev/null | grep -q '^pdo_mysql$'; then
    PKGS+=(php-mysql)
fi
apt_install "${PKGS[@]}"

# --- 2. PHP + Node dependencies -------------------------------------------------

log "Installing Composer dependencies (repo root)"
composer install --no-interaction

log "Installing npm dependencies (api/server)"
(cd api/server && npm install --no-audit --no-fund)

# --- 3. Database -------------------------------------------------------------

log "Provisioning the local database (scripts/dbUpdate.sh)"
bash "$REPO_ROOT/scripts/dbUpdate.sh"

# --- 4. .env scaffolding ---------------------------------------------------------

# Repo-root .env: what api/db/bootstrap.php loads when running from the repo.
if [ -f .env ]; then
    log ".env already exists — leaving it untouched."
else
    if [ -f "$HOME/myscene-db/.env" ]; then
        log "Creating .env from ~/myscene-db/.env (generated by dbUpdate.sh)"
        cp "$HOME/myscene-db/.env" .env
    else
        cp .env.example .env
    fi
    chmod 600 .env
fi

# Node API .env: points the local setup at the PHP db-api on port 8080.
if [ -f api/server/.env ]; then
    log "api/server/.env already exists — leaving it untouched."
else
    log "Creating api/server/.env"
    cp api/server/.env.example api/server/.env
    # DB_API_BASE_URL must match where you serve the PHP db-api locally.
    sed -i 's|^DB_API_BASE_URL=.*|DB_API_BASE_URL=http://127.0.0.1:8080|' api/server/.env
    sed -i 's|^ALLOWED_ORIGINS=.*|ALLOWED_ORIGINS=https://myscene.live,http://localhost:8000,http://127.0.0.1:8000,http://localhost:5500|' api/server/.env
    chmod 600 api/server/.env
fi

# --- Summary ------------------------------------------------------------------------

cat <<'EOF'

[myscene] Local setup complete. Start the site with three terminals:

  Terminal 1:  php -S localhost:8080 -t api/db      # PHP db-api (talks to MySQL)
  Terminal 2:  cd api/server && npm start           # Node API on http://localhost:3000
  Terminal 3:  php -S localhost:8000 -t public      # Website

  Then open: http://localhost:8000

Notes:
  - The pages default to the production API (https://api.myscene.live).
    To use the local Node API, set window.MYSCENE_API_BASE = 'http://localhost:3000'
    in the page before the site scripts load (see public/js/api.js).
  - Fill in LOCATIONIQ_API_KEY / LASTFM_API_KEY in api/server/.env to enable
    geocoding and genre features.
  - Database credentials: .env (repo root) and ~/myscene-db/.env
EOF
