#!/usr/bin/env bash

# =============================================================================
# MyScene — website update script
#
# Run this on the web host. It is idempotent: on a fresh machine it installs
# nginx and starts it; on later runs it just redeploys the latest static
# files and reloads nginx.
#
# What it deploys:
#   public/  ->  /var/www/html   (the only part served to browsers)
#
# Optional: point the deployed site at a specific API server.
#   MYSCENE_API_BASE="http://api.example.com:3000" ./webUpdate.sh
# When set, the deploy injects a small js/myscene-config.js (loaded before
# the site scripts) that sets window.MYSCENE_API_BASE — the mechanism the
# frontend already supports. Without it, the site keeps its built-in default
# (https://api.myscene.live).
#
# Usage:
#   ./webUpdate.sh
#   MYSCENE_API_BASE="http://192.168.1.20:3000" ./webUpdate.sh
# =============================================================================

set -euo pipefail

REPO_URL="${MYSCENE_REPO_URL:-https://github.com/BradenLemna/myscene.git}"
GIT_DIR="$HOME/myscene-git"
WEB_ROOT="/var/www/html"
SELF_NAME="$(basename "$0")"

# --- small helpers ----------------------------------------------------------

SUDO=""
if [ "$(id -u)" -ne 0 ]; then
    if command -v sudo >/dev/null 2>&1; then
        SUDO="sudo"
    else
        echo "[myscene][ERROR] This script needs root (or passwordless sudo) to manage packages/services." >&2
        exit 1
    fi
fi

log()  { echo "[myscene] $*"; }
warn() { echo "[myscene][WARN] $*" >&2; }
die()  { echo "[myscene][ERROR] $*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

apt_install() {
    local missing=()
    for pkg in "$@"; do
        dpkg -s "$pkg" >/dev/null 2>&1 || missing+=("$pkg")
    done
    [ ${#missing[@]} -eq 0 ] && return 0
    log "Installing packages: ${missing[*]}"
    DEBIAN_FRONTEND=noninteractive $SUDO apt-get update -qq
    DEBIAN_FRONTEND=noninteractive $SUDO apt-get install -y --no-install-recommends "${missing[@]}"
}

have_systemd() { [ -d /run/systemd/system ]; }

svc_running() { # $1 = unit, $2 = service name
    if have_systemd; then
        systemctl is-active --quiet "$1"
    else
        service "$2" status >/dev/null 2>&1
    fi
}

svc_start() { # $1 = unit, $2 = service name, $3 = direct fallback command
    if svc_running "$1" "$2"; then
        return 0
    fi
    if have_systemd; then
        $SUDO systemctl start "$1" || true
        $SUDO systemctl enable "$1" || true
    else
        $SUDO service "$2" start || $SUDO bash -c "nohup $3" || true
    fi
}

svc_reload() { # $1 = unit, $2 = service name
    if have_systemd; then
        $SUDO systemctl reload "$1" 2>/dev/null || $SUDO systemctl restart "$1"
    else
        $SUDO service "$2" reload 2>/dev/null || $SUDO service "$2" restart
    fi
}

fetch_repo() {
    if [ -d "$GIT_DIR/.git" ]; then
        log "Updating existing checkout at $GIT_DIR"
        local branch
        branch="$(git -C "$GIT_DIR" symbolic-ref --short -q HEAD || echo main)"
        if git -C "$GIT_DIR" fetch --quiet origin "$branch" \
           && git -C "$GIT_DIR" checkout --quiet -B "$branch" "origin/$branch"; then
            return 0
        fi
        warn "Pull failed — re-cloning $GIT_DIR"
        rm -rf "$GIT_DIR"
    fi
    log "Cloning $REPO_URL -> $GIT_DIR"
    git clone --quiet "$REPO_URL" "$GIT_DIR"
}

self_update() {
    if [ -f "$GIT_DIR/scripts/$SELF_NAME" ]; then
        cp "$GIT_DIR/scripts/$SELF_NAME" "$HOME/$SELF_NAME" 2>/dev/null && chmod +x "$HOME/$SELF_NAME" || true
    fi
}



# --- 1. nginx -----------------------------------------------------------------

log "Checking nginx..."
if ! have nginx; then
    apt_install nginx
fi

# --- 2. Fresh repository code --------------------------------------------------

fetch_repo
[ -d "$GIT_DIR/public" ] || die "public/ not found in $GIT_DIR"

# --- 3. Deploy the web root ------------------------------------------------------

log "Deploying website -> $WEB_ROOT"
$SUDO mkdir -p "$WEB_ROOT"
$SUDO cp -r "$GIT_DIR/public/." "$WEB_ROOT/"

# Optional: pin the deployed site to a specific API base URL.
if [ -n "${MYSCENE_API_BASE:-}" ]; then
    API_BASE="${MYSCENE_API_BASE%/}"
    log "Injecting API base '$API_BASE' into the deployed pages"
    $SUDO tee "$WEB_ROOT/js/myscene-config.js" > /dev/null <<EOF
// Generated by webUpdate.sh — do not edit by hand.
window.MYSCENE_API_BASE = '$API_BASE';
EOF
    html=""
    pat=""
    while IFS= read -r html; do
        [ -f "$html" ] || continue
        grep -q "myscene-config\.js" "$html" && continue
        if grep -q 'src="\.\./js/' "$html"; then
            pat='../js/'
            pat_re='\.\.\/js\/'
        else
            pat='js/'
            pat_re='js\/'
        fi
        $SUDO sed -i "0,/<script[^>]*src=\"${pat_re}/s||<script src=\"${pat}myscene-config.js\"></script>\n&|" "$html"
    done < <(find "$WEB_ROOT" -maxdepth 2 -name '*.html' -type f)
    log "API base configured."
else
    log "MYSCENE_API_BASE not set — the site keeps its built-in API base (https://api.myscene.live)."
fi

# --- 4. Start / reload nginx ------------------------------------------------------

log "Starting/reloading nginx"
if svc_running nginx nginx; then
    svc_reload nginx nginx
else
    svc_start nginx nginx "nginx"
    # Fallback for exotic setups where neither systemctl nor the init script
    # works: ask the nginx binary directly.
    if ! svc_running nginx nginx; then
        $SUDO nginx -t && { $SUDO nginx -s reload 2>/dev/null || $SUDO nginx; }
    fi
fi

# --- 5. Health check ---------------------------------------------------------------

log "Waiting for the website (http://127.0.0.1/)..."
ok=0
for _ in $(seq 1 15); do
    code="$(curl -fsS -m 5 -o /dev/null -w '%{http_code}' http://127.0.0.1/ 2>/dev/null || true)"
    if [ "$code" = "200" ]; then
        ok=1
        break
    fi
    sleep 1
done
if [ "$ok" -eq 1 ]; then
    log "Website is up: http://127.0.0.1/ (HTTP 200)"
else
    warn "Website not responding on port 80 — check 'nginx -t' and the nginx error log"
fi

log "Web update complete."
self_update
